name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js (pnpm assumes Node.js is already installed)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # You can change this to your desired version of Node.js

      # Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install

      # Build the project using pnpm
      - name: Build project
        run: pnpm run build # This assumes you have a "build" script in your package.json

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Path to your build directory
          publish_branch: gh-pages # The branch where GitHub Pages is served from
